FROM node:22.18.0 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install --omit-dev

COPY . .
RUN npm run build

FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html

COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]
