// Mock data for beats - shared across different views
export const mockedBeats = [
  {
    _id: "1",
    title: "Summer Vibes",
    artist: "DJ Producer",
    genre: "Hip Hop",
    bpm: 120,
    key: "C#",
    duration: 180,
    tags: ["chill", "summer", "trap"],
    pricing: { isFree: false, price: 29.99, currency: "USD" },
    stats: { plays: 1500, downloads: 200, likes: 350, comments: 45 },
    createdAt: new Date("2023-05-15T10:00:00Z"),
    mood: "Happy",
    license: "Exclusive",
  },
  {
    _id: "2",
    title: "Chill Lo-Fi",
    artist: "BeatMaker",
    genre: "Lo-Fi",
    bpm: 90,
    key: "A#",
    duration: 150,
    tags: ["lofi", "chill", "relax"],
    pricing: { isFree: true, price: 0, currency: "USD" },
    stats: { plays: 8000, downloads: 1200, likes: 2100, comments: 180 },
    createdAt: new Date("2023-04-20T15:30:00Z"),
    mood: "Relaxed",
    license: "Free",
  },
  {
    _id: "3",
    title: "Trap Banger",
    artist: "TrapGod",
    genre: "Trap",
    bpm: 150,
    key: "G",
    duration: 165,
    tags: ["trap", "banger", "hard"],
    pricing: { isFree: false, price: 19.99, currency: "USD" },
    stats: { plays: 12000, downloads: 800, likes: 1800, comments: 120 },
    createdAt: new Date("2023-06-10T18:45:00Z"),
    mood: "Energetic",
    license: "Lease",
  },
  {
    _id: "4",
    title: "Midnight Dreams",
    artist: "NightOwl",
    genre: "Ambient",
    bpm: 80,
    key: "F",
    duration: 240,
    tags: ["ambient", "calm", "night"],
    pricing: { isFree: false, price: 34.99, currency: "USD" },
    stats: { plays: 3200, downloads: 150, likes: 680, comments: 32 },
    createdAt: new Date("2023-07-22T02:15:00Z"),
    mood: "Dreamy",
    license: "Exclusive",
  },
  {
    _id: "5",
    title: "Boom Bap Classic",
    artist: "OldSchool",
    genre: "Boom Bap",
    bpm: 95,
    key: "D",
    duration: 195,
    tags: ["boom bap", "classic", "90s"],
    pricing: { isFree: false, price: 24.99, currency: "USD" },
    stats: { plays: 6700, downloads: 420, likes: 1240, comments: 89 },
    createdAt: new Date("2023-08-05T12:00:00Z"),
    mood: "Nostalgic",
    license: "Lease",
  },
  {
    _id: "6",
    title: "Future Bass Drop",
    artist: "Synth Master",
    genre: "Future Bass",
    bpm: 140,
    key: "E",
    duration: 210,
    tags: ["future bass", "synth", "melodic"],
    pricing: { isFree: true, price: 0, currency: "USD" },
    stats: { plays: 15000, downloads: 2100, likes: 3500, comments: 250 },
    createdAt: new Date("2023-09-12T16:30:00Z"),
    mood: "Uplifting",
    license: "Free",
  },
  {
    _id: "7",
    title: "Dark Drill",
    artist: "UK Producer",
    genre: "Drill",
    bpm: 140,
    key: "C",
    duration: 175,
    tags: ["drill", "dark", "uk"],
    pricing: { isFree: false, price: 39.99, currency: "USD" },
    stats: { plays: 9800, downloads: 650, likes: 1950, comments: 145 },
    createdAt: new Date("2023-10-01T20:00:00Z"),
    mood: "Aggressive",
    license: "Exclusive",
  },
  {
    _id: "8",
    title: "R&B Smooth",
    artist: "Soul Vibes",
    genre: "R&B",
    bpm: 75,
    key: "Bb",
    duration: 220,
    tags: ["rnb", "smooth", "soul"],
    pricing: { isFree: false, price: 27.99, currency: "USD" },
    stats: { plays: 4300, downloads: 280, likes: 890, comments: 67 },
    createdAt: new Date("2023-10-18T14:45:00Z"),
    mood: "Romantic",
    license: "Lease",
  },
  {
    _id: "9",
    title: "Latin Heat",
    artist: "Reggaeton King",
    genre: "Reggaeton",
    bpm: 95,
    key: "Am",
    duration: 190,
    tags: ["reggaeton", "latin", "party"],
    pricing: { isFree: false, price: 29.99, currency: "USD" },
    stats: { plays: 18500, downloads: 1400, likes: 4200, comments: 320 },
    createdAt: new Date("2023-10-25T19:30:00Z"),
    mood: "Party",
    license: "Lease",
  },
  {
    _id: "10",
    title: "Jazz Hop Fusion",
    artist: "Jazz Beats",
    genre: "Jazz Hop",
    bpm: 88,
    key: "Dm",
    duration: 205,
    tags: ["jazz", "hip hop", "fusion"],
    pricing: { isFree: true, price: 0, currency: "USD" },
    stats: { plays: 7200, downloads: 890, likes: 1650, comments: 98 },
    createdAt: new Date("2023-11-03T11:20:00Z"),
    mood: "Sophisticated",
    license: "Free",
  },
  {
    _id: "11",
    title: "EDM Anthem",
    artist: "Festival Pro",
    genre: "EDM",
    bpm: 128,
    key: "G",
    duration: 235,
    tags: ["edm", "festival", "anthem"],
    pricing: { isFree: false, price: 44.99, currency: "USD" },
    stats: { plays: 22000, downloads: 1850, likes: 5100, comments: 410 },
    createdAt: new Date("2023-11-08T08:00:00Z"),
    mood: "Euphoric",
    license: "Exclusive",
  },
  {
    _id: "12",
    title: "Afrobeat Groove",
    artist: "Lagos Sound",
    genre: "Afrobeat",
    bpm: 110,
    key: "F#",
    duration: 198,
    tags: ["afrobeat", "groove", "african"],
    pricing: { isFree: false, price: 32.99, currency: "USD" },
    stats: { plays: 11200, downloads: 720, likes: 2340, comments: 156 },
    createdAt: new Date("2023-11-12T17:15:00Z"),
    mood: "Groovy",
    license: "Lease",
  },
  {
    _id: "13",
    title: "Psychedelic Trip",
    artist: "Mind Bender",
    genre: "Psychedelic",
    bpm: 125,
    key: "E",
    duration: 270,
    tags: ["psychedelic", "experimental", "trippy"],
    pricing: { isFree: false, price: 41.99, currency: "USD" },
    stats: { plays: 5400, downloads: 340, likes: 920, comments: 54 },
    createdAt: new Date("2023-11-15T22:30:00Z"),
    mood: "Hypnotic",
    license: "Lease",
  },
];

export const allColumns = [
  { key: "artist", label: "Artist" },
  { key: "genre", label: "Genre" },
  { key: "bpm", label: "BPM" },
  { key: "key", label: "Key" },
  { key: "duration", label: "Duration" },
  { key: "price", label: "Price" },
  { key: "plays", label: "Plays" },
  { key: "downloads", label: "Downloads" },
  { key: "likes", label: "Likes" },
  { key: "comments", label: "Comments" },
  { key: "mood", label: "Mood" },
  { key: "license", label: "License" },
  { key: "createdAt", label: "Upload Date" },
];
